# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        MRS\UserBundle\Entity\User: sha512
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory:
            #memory: ~
       db_user_provider:
            entity: { class: UserBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: /logincheck
                login_path: /login
                default_target_path: /
            logout:
                path: /logout
                target: /login
            remember_me:
                secret: "%secret%"
                name: 'sge_escolar'
                lifetime: 86400
                always_remember_me: true
            anonymous: ~
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
          - { path: ^/cadastro, roles: ROLE_ADMIN }
          - { path: ^/registro, roles: ROLE_USER }
          - { path: ^/home, roles: ROLE_USER }
          - { path: ^/admin, roles: ROLE_ADMIN }
          - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    role_hierarchy:
         ROLE_ADMIN: [ROLE_USER, ROLE_READ]